### ISSUE TITLE
Rooms with voice messages do not open

### ISSUE THREAD

**Issue by affenull2345** [farooqkz/chooj#90]
After sending a voice message in a room, chooj can't open the room anymore, it just stops responding when I click on the room in the menu. The console shows `Uncaught (in promise) TypeError: mxcUrl is undefined` errors originating in the mxcMediaToHttp function called from IRCLikeMessageItemAudio.

**Comment by plan5** [comment]
Fixed the autoplay issue for 8110 and 8000. See comments in the PR.

**Comment by farooqkz** [comment]
@affenull2345 Is the bug still there? let me know to reopen if this is the case.
